// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfaoqtariymsfsrvynqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmYW9xdGFyaXltc2ZzcnZ5bnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyOTM5MTcsImV4cCI6MjA2NDg2OTkxN30.YRHU2QABqhTECrfvlTjCWr9j5gSgPVTHxblkT2cz1KQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);